version: '3.0'
services:
  backend:
    build:
      context: .
    ports: 
      - "5000:5000"
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root 
      MYSQL_PASSWORD: abc@123
      MYSQL_DB: two_tier
  mysql:
    image: mysql:5.7
    environment:
     MYSQL_ROOT_PASSWORD: abc@123
     MYSQL_USER: devops
     MYSQL_DATABASE: two_tier
     MYSQL_PASSWORD: devops
    volumes:
     - my-datavolume:/var/lib/mysql
volumes:
  my-datavolume:
